BUNDLE_NAME = CrystalPreferences
CrystalPreferences_FILES = $(wildcard Controllers/*.m Cells/*.m)
CrystalPreferences_FRAMEWORKS = UIKit
CrystalPreferences_PRIVATE_FRAMEWORKS = Preferences
CrystalPreferences_INSTALL_PATH = /Library/PreferenceBundles
CrystalPreferences_CFLAGS = -fobjc-arc

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk
